services:
  cryptobuyer-web:
    build: ./cryptobuyer-web
    container_name: cryptobuyer-web
    restart: unless-stopped
    tty: true
    volumes:
      - ./cryptobuyer-web:/usr/local/app
      - /usr/local/app/node_modules
    command: yarn dev
    networks:
      cb-net:
        ipv4_address: 210.10.10.20

  cryptobuyer-admin:
    image: wordpress
    container_name: cryptobuyer-admin
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: cryptobuyer-db
      WORDPRESS_DB_USER: cryptobuyer
      WORDPRESS_DB_PASSWORD: cryptobuyer123
      WORDPRESS_DB_NAME: cryptobuyer
      WORDPRESS_FS_METHOD: direct
    volumes:
      - ./cryptobuyer-admin:/var/www/html
    networks:
      cb-net:
        ipv4_address: 210.10.10.21

  cryptobuyer-db:
    image: mysql:5.7
    container_name: cryptobuyer-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: cryptobuyer
      MYSQL_USER: crypto
      MYSQL_PASSWORD: testing-cryptobuyer
      MYSQL_RANDOM_ROOT_PASSWORD: "1"
    volumes:
      - ./cryptobuyer-db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    environment:
      - PMA_HOST=cryptobuyer-db
      - PMA_PORT=3306
    networks:
      cb-net:
        ipv4_address: 210.10.10.22

networks:
  cb-net:
    driver: bridge
    ipam:
      config:
        - subnet: 210.10.10.1/24
