services:
  cryptobuyer-admin:
    image: wordpress
    container_name: cryptobuyer-admin
    restart: unless-stopped
    ports:
      - 8891:80
    environment:
      WORDPRESS_DB_HOST: cryptobuyer-db
      WORDPRESS_DB_USER: buscao
      WORDPRESS_DB_PASSWORD: buscao123
      WORDPRESS_DB_NAME: buscao
      WORDPRESS_FS_METHOD: direct
    volumes:
      - ./cryptobuyer-admin:/var/www/html

  cryptobuyer-db:
    image: mysql:5.7
    container_name: cryptobuyer-db
    restart: unless-stopped
    ports:
      - "3333:3306"
    environment:
      MYSQL_DATABASE: buscao
      MYSQL_USER: buscao
      MYSQL_PASSWORD: buscao123
      MYSQL_RANDOM_ROOT_PASSWORD: "1"
    volumes:
      - ./cryptobuyer-db:/var/lib/mysql