services:
  cryptobuyer-admin:
    image: wordpress
    container_name: cryptobuyer-admin
    restart: unless-stopped
    ports:
      - 8891:80
    environment:
      WORDPRESS_DB_HOST: database.thecodeworkers.com
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: cryptobuyer
      WORDPRESS_FS_METHOD: direct
    volumes:
      - ./cryptobuyer-admin:/var/www/html