services:
  cryptobuyer-web:
    build: ./cryptobuyer-web
    container_name: cryptobuyer-web
    restart: unless-stopped
    tty: true
    volumes:
      - ./cryptobuyer-web:/usr/local/app
      - /usr/local/app/node_modules
    ports:
      - "3000:3000"
    command: yarn dev

  cryptobuyer-admin:
    image: wordpress
    container_name: cryptobuyer-admin
    restart: unless-stopped
    ports:
      - 8891:80
    environment:
      WORDPRESS_DB_HOST: cryptobuyer-db
      WORDPRESS_DB_USER: cryptobuyer
      WORDPRESS_DB_PASSWORD: cryptobuyer123
      WORDPRESS_DB_NAME: cryptobuyer
      WORDPRESS_FS_METHOD: direct
    volumes:
      - ./cryptobuyer-admin:/var/www/html

  cryptobuyer-db:
    image: mysql:5.7
    container_name: cryptobuyer-db
    restart: unless-stopped
    ports:
      - "3333:3306"
    environment:
      MYSQL_DATABASE: cryptobuyer
      MYSQL_USER: cryptobuyer
      MYSQL_PASSWORD: cryptobuyer123
      MYSQL_ROOT_PASSWORD: cryptobuyerdev
    volumes:
      - ./cryptobuyer-db:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8100:80
    environment:
      - PMA_HOST=cryptobuyer-db
      - PMA_PORT=3306
      - PMA_USER=cryptobuyer
      - PMA_PASSWORD=cryptobuyer123
      