services:
  cryptobuyer-web:
    build: ./cryptobuyer-web
    container_name: cryptobuyer-web
    restart: unless-stopped
    tty: true
    volumes:
      - ./cryptobuyer-web:/usr/local/app
      - /usr/local/app/node_modules
    ports:
      - "3000:3000"
    command: yarn dev

  cryptobuyer-admin:
    image: wordpress
    container_name: cryptobuyer-admin
    restart: unless-stopped
    ports:
      - 8891:80
    environment:
      WORDPRESS_DB_HOST: database.thecodeworkers.com
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: cryptobuyer_dev
      WORDPRESS_FS_METHOD: direct
    volumes:
      - ./cryptobuyer-admin:/var/www/html
