services:
  cryptobuyer-web-test:
    build: ./cryptobuyer-web-test
    container_name: cryptobuyer-web-test
    restart: unless-stopped
    tty: true
    volumes:
      - ./cryptobuyer-web:/usr/local/app
      - /usr/local/app/node_modules
    command: yarn dev
    networks:
      cb-net:
        ipv4_address: 210.10.10.20

  cryptobuyer-admin-test:
    image: wordpress
    container_name: cryptobuyer-admin-test
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: cryptobuyer-db-test
      WORDPRESS_DB_USER: cryptobuyer-test
      WORDPRESS_DB_PASSWORD: cryptobuyer123
      WORDPRESS_DB_NAME: cryptobuyer-test
      WORDPRESS_FS_METHOD: direct
    volumes:
      - ./cryptobuyer-admin:/var/www/html
    networks:
      cb-net:
        ipv4_address: 210.10.10.21

  cryptobuyer-db-test:
    image: mysql:5.7
    container_name: cryptobuyer-db-test
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: cryptobuyer-test
      MYSQL_USER: cryptobuyer-test
      MYSQL_PASSWORD: cryptobuyer123
      MYSQL_RANDOM_ROOT_PASSWORD: "1"
    volumes:
      - ./cryptobuyer-db-test:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    environment:
      - PMA_HOST=cryptobuyer-db-test
      - PMA_PORT=3306
    networks:
      cb-net:
        ipv4_address: 210.10.10.22

networks:
  cb-net:
    driver: bridge
    ipam:
      config:
        - subnet: 210.10.10.1/24
